### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [geowatson/loadtest#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary loadtest -w /tmp/ext loadtest==0.0.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting loadtest==0.0.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/322/6be43bad78374/loadtest-0.0.2.tar.gz (2.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-u7vkw57w/loadtest/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-u7vkw57w/loadtest/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-u7vkw57w/loadtest/pip-egg-info
         cwd: /tmp/pip-wheel-u7vkw57w/loadtest/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-u7vkw57w/loadtest/setup.py", line 8, in <module>
        with open('requirements.txt', encoding='utf-8') as fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by geowatson** [comment]
thanks for the issue, will fix this in next build
